spring.application.name=api-gateway
server.port=8080

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Dotenv (.env) Configuration
springdotenv.directory=${SPRINGDOTENV_DIRECTORY:api-gateway}
springdotenv.filename=${SPRINGDOTENV_FILENAME:.env}
springdotenv.ignoreIfMissing=false

# JWT Configuration
jwt.secret=${JWT_SECRET}
